# Generated by Django 2.1.3 on 2018-11-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set(),
        ),
    ]
